name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      # - name: Run unit tests
      #   run: go test ./...

      - name: Run unit tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Test security check
        run: gosec ./...

  style:
    name: Style
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"
                
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Perform staticcheck
        run: staticcheck ./...
